name = "referralform-mailer-api"
main = "src/index.js"
compatibility_date = "2025-07-18"

[vars]
ALLOWED_ORIGIN = "*"
MAIL_TO = "venkatrx1@gmail.com, fannininfusionrx@gmail.com, prchalla@gmail.com, +19034305128@fax.plus"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
