name = "careplasma-mailer-api"
main = "src/index.js"
compatibility_date = "2025-07-18"

[vars]
ALLOWED_ORIGIN = "*"
MAIL_TO = "venkatrx1@gmail.com, info@careplasma.com"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
